In [9]:
%pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [10]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_excel('flight_price.xlsx')

df.head()

       Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
0       IndiGo      24/03/2019  Banglore  ...    non-stop         No info   3897
1    Air India       1/05/2019   Kolkata  ...     2 stops         No info   7662
2  Jet Airways       9/06/2019     Delhi  ...     2 stops         No info  13882
3       IndiGo      12/05/2019   Kolkata  ...      1 stop         No info   6218
4       IndiGo      01/03/2019  Banglore  ...      1 stop         No info  13302

[5 rows x 11 columns]

In [12]:
df.shape

(10683, 11)

In [13]:
df.tail()

           Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
10678     Air Asia       9/04/2019   Kolkata  ...    non-stop         No info   4107
10679    Air India      27/04/2019   Kolkata  ...    non-stop         No info   4145
10680  Jet Airways      27/04/2019  Banglore  ...    non-stop         No info   7229
10681      Vistara      01/03/2019  Banglore  ...    non-stop         No info  12648
10682    Air India       9/05/2019     Delhi  ...     2 stops         No info  11753

[5 rows x 11 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [15]:
df.describe()
df.head()

       Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
0       IndiGo      24/03/2019  Banglore  ...    non-stop         No info   3897
1    Air India       1/05/2019   Kolkata  ...     2 stops         No info   7662
2  Jet Airways       9/06/2019     Delhi  ...     2 stops         No info  13882
3       IndiGo      12/05/2019   Kolkata  ...      1 stop         No info   6218
4       IndiGo      01/03/2019  Banglore  ...      1 stop         No info  13302

[5 rows x 11 columns]

In [16]:
##feature engineering

df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [17]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [18]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [20]:
#drop date of journey
df.drop('Date_of_Journey', axis=1, inplace=True)

In [21]:
df.head()

       Airline    Source Destination  ... Date Month  Year
0       IndiGo  Banglore   New Delhi  ...   24     3  2019
1    Air India   Kolkata    Banglore  ...    1     5  2019
2  Jet Airways     Delhi      Cochin  ...    9     6  2019
3       IndiGo   Kolkata    Banglore  ...   12     5  2019
4       IndiGo  Banglore   New Delhi  ...    1     3  2019

[5 rows x 13 columns]

In [22]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [23]:
df['Arrival_hour']= df['Arrival_Time'].str.split(":").str[0]
df['Arrival_min']= df['Arrival_Time'].str.split(":").str[1]

In [24]:
df.head(2)

     Airline    Source Destination  ...  Year Arrival_hour Arrival_min
0     IndiGo  Banglore   New Delhi  ...  2019           01          10
1  Air India   Kolkata    Banglore  ...  2019           13          15

[2 rows x 15 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_hour     10683 non-null  object
 14  Arrival_min      10683 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.2+ MB

In [26]:
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_min']=df['Arrival_min'].astype(int)

In [27]:
df.drop('Arrival_Time', axis=1 , inplace=True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_hour     10683 non-null  int64
 13  Arrival_min      10683 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

In [29]:
df['Departure_hour']= df['Dep_Time'].str.split(":").str[0]
df['Departure_min']= df['Dep_Time'].str.split(":").str[1]

In [30]:
df.head()

       Airline    Source Destination  ... Arrival_min Departure_hour Departure_min
0       IndiGo  Banglore   New Delhi  ...          10             22            20
1    Air India   Kolkata    Banglore  ...          15             05            50
2  Jet Airways     Delhi      Cochin  ...          25             09            25
3       IndiGo   Kolkata    Banglore  ...          30             18            05
4       IndiGo  Banglore   New Delhi  ...          35             16            50

[5 rows x 16 columns]

In [31]:
df['Departure_hour']= df['Departure_hour'].astype(int)
df['Departure_min']= df['Departure_min'].astype(int)

In [32]:
df.head()

       Airline    Source  ... Departure_hour Departure_min
0       IndiGo  Banglore  ...             22            20
1    Air India   Kolkata  ...              5            50
2  Jet Airways     Delhi  ...              9            25
3       IndiGo   Kolkata  ...             18             5
4       IndiGo  Banglore  ...             16            50

[5 rows x 16 columns]

In [33]:
df.drop('Dep_Time', axis=1, inplace=True)

In [34]:
df.head()

       Airline    Source  ... Departure_hour Departure_min
0       IndiGo  Banglore  ...             22            20
1    Air India   Kolkata  ...              5            50
2  Jet Airways     Delhi  ...              9            25
3       IndiGo   Kolkata  ...             18             5
4       IndiGo  Banglore  ...             16            50

[5 rows x 15 columns]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_hour     10683 non-null  int64
 12  Arrival_min      10683 non-null  int64
 13  Departure_hour   10683 non-null  int64
 14  Departure_min    10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [36]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [37]:
df[df["Total_Stops"].isnull()]

        Airline Source Destination  ... Arrival_min Departure_hour Departure_min
9039  Air India  Delhi      Cochin  ...          25              9            45

[1 rows x 15 columns]

In [38]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop': 0, '2 stops':2, '1 stop' :1, '3 stops' : 3, '4 stops':4,np.nan:1})

In [39]:
df[df["Total_Stops"].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_min, Departure_hour, Departure_min]
Index: []

In [40]:
df.head(2)

     Airline    Source Destination  ... Arrival_min Departure_hour  Departure_min
0     IndiGo  Banglore   New Delhi  ...          10             22             20
1  Air India   Kolkata    Banglore  ...          15              5             50

[2 rows x 15 columns]

In [41]:
df.drop('Route', axis=1, inplace=True)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Duration         10683 non-null  object
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  object
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   Month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_min      10683 non-null  int64
 12  Departure_hour   10683 non-null  int64
 13  Departure_min    10683 non-null  int64
dtypes: int64(9), object(5)
memory usage: 1.1+ MB

In [43]:
df.head(2)

     Airline    Source Destination  ... Arrival_min  Departure_hour Departure_min
0     IndiGo  Banglore   New Delhi  ...          10              22            20
1  Air India   Kolkata    Banglore  ...          15               5            50

[2 rows x 14 columns]

In [44]:
df['Duration']= df['Duration'].str.replace('h','')
df['Duration']= df['Duration'].str.replace('m','')

In [45]:
df['Duration']

0        2 50
1        7 25
2          19
3        5 25
4        4 45
         ...
10678    2 30
10679    2 35
10680       3
10681    2 40
10682    8 20
Name: Duration, Length: 10683, dtype: object

In [46]:
df['Duration_hour']= df['Duration'].str.split(' ').str[0]
df['Duration_min']= df['Duration'].str.split(' ').str[1]

In [47]:
df.head()

       Airline    Source Destination  ... Departure_min  Duration_hour Duration_min
0       IndiGo  Banglore   New Delhi  ...            20              2           50
1    Air India   Kolkata    Banglore  ...            50              7           25
2  Jet Airways     Delhi      Cochin  ...            25             19          NaN
3       IndiGo   Kolkata    Banglore  ...             5              5           25
4       IndiGo  Banglore   New Delhi  ...            50              4           45

[5 rows x 16 columns]

In [48]:
df['Duration_hour'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
10678    False
10679    False
10680    False
10681    False
10682    False
Name: Duration_hour, Length: 10683, dtype: bool

In [49]:
df['Duration_min'].isnull()

0        False
1        False
2         True
3        False
4        False
         ...
10678    False
10679    False
10680     True
10681    False
10682    False
Name: Duration_min, Length: 10683, dtype: bool

In [50]:
df['Duration_min']= df['Duration_min'].replace(np.nan,0)

In [51]:
df['Duration_min'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
10678    False
10679    False
10680    False
10681    False
10682    False
Name: Duration_min, Length: 10683, dtype: bool

In [52]:
df.head()

       Airline    Source Destination  ... Departure_min  Duration_hour Duration_min
0       IndiGo  Banglore   New Delhi  ...            20              2           50
1    Air India   Kolkata    Banglore  ...            50              7           25
2  Jet Airways     Delhi      Cochin  ...            25             19            0
3       IndiGo   Kolkata    Banglore  ...             5              5           25
4       IndiGo  Banglore   New Delhi  ...            50              4           45

[5 rows x 16 columns]

In [53]:
df.drop('Duration', axis=1, inplace=True)

In [54]:
df['Duration_hour'] = df['Duration_hour'].astype(int)
df['Duration_min'] = df['Duration_min'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Total_Stops      10683 non-null  int64
 4   Additional_Info  10683 non-null  object
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_hour     10683 non-null  int64
 10  Arrival_min      10683 non-null  int64
 11  Departure_hour   10683 non-null  int64
 12  Departure_min    10683 non-null  int64
 13  Duration_hour    10683 non-null  int64
 14  Duration_min     10683 non-null  int64
dtypes: int64(11), object(4)
memory usage: 1.2+ MB

In [55]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [56]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in e:\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in e:\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in e:\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in e:\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in e:\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [57]:
from sklearn.preprocessing import OneHotEncoder

In [2]:
encoder = OneHotEncoder()

In [58]:
encoder.fit_transform(df[['Airline','Source', 'Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))

In [59]:
pd.DataFrame(encoder.fit_transform(df[['Airline','Source', 'Destination']]).toarray(), columns=encoder.get_feature_names_out(['Airline','Source', 'Destination']))

       Airline_Air Asia  ...  Destination_New Delhi
0                   0.0  ...                    1.0
1                   0.0  ...                    0.0
2                   0.0  ...                    0.0
3                   0.0  ...                    0.0
4                   0.0  ...                    1.0
...                 ...  ...                    ...
10678               1.0  ...                    0.0
10679               0.0  ...                    0.0
10680               0.0  ...                    0.0
10681               0.0  ...                    1.0
10682               0.0  ...                    0.0

[10683 rows x 23 columns]