Pandas is a powerfull data manipulation library in python widely used for data analysis and data cleaning it provides two primary data structures : series and Dataframe. A series is a one dimensional arrey like object while a Dataframe is a two-dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [3]:
## series 
# pandas is a one-dimension array like object 

import pandas as pd
data =  [1,2,3,4,5,6]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#create series from dictionary
data = {'a': 1 , 'b':2}
series_dic = pd.Series(data)
print(series_dic)

a    1
b    2
dtype: int64

In [5]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data , index= index)

a    10
b    20
c    30
dtype: int64

In [8]:
#Data frame
## ceate aData frame from dict of list
data = { 
    'name' : ['krish', 'John','jack' ],
    "age" : [25,30,45],
    "city":['inodre','new york','florida']
}
df = pd.DataFrame(data=data)
print(df)
print(type(df))

    name  age      city
0  krish   25    inodre
1   John   30  new york
2   jack   45   florida
<class 'pandas.core.frame.DataFrame'>

In [10]:
#create a datafrane from lst of dict 

data = [
    {'name' : 'krish', 'age' : 25 , 'city': 'banglore'},
    {'name' : 'John', 'age' : 25 , 'city': 'banglore'},
    {'name' : 'Aman', 'age' : 25 , 'city': 'banglore'},
    {'name' : 'Anand', 'age' : 25 , 'city': 'banglore'},
]
df = pd.DataFrame(data=data)
print(df)
print(type(df))

    name  age      city
0  krish   25  banglore
1   John   25  banglore
2   Aman   25  banglore
3  Anand   25  banglore
<class 'pandas.core.frame.DataFrame'>

In [11]:
df =pd.read_csv('annual-enterprise.csv')
df.head(5)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [12]:
df.tail(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
55610,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H32,Current liabilities,Financial position,"10,212","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55611,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H33,Other liabilities,Financial position,"2,220","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55612,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H34,Total income per employee count,Financial ratios,"523,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55613,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"17,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55614,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H36,Current ratio,Financial ratios,91,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [14]:
#accessing data from Data frame
data
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df['Year']
# using  this we can view year column data

0        2024
1        2024
2        2024
3        2024
4        2024
         ...
55615    2013
55616    2013
55617    2013
55618    2013
55619    2013
Name: Year, Length: 55620, dtype: int64

In [17]:
type(df['Year'])

pandas.core.series.Series

In [31]:
df.loc[0:10]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
5,2024,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,71493,ANZSIC06 divisions A-S (excluding classes K633...
6,2024,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,8540,ANZSIC06 divisions A-S (excluding classes K633...
7,2024,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,32896,ANZSIC06 divisions A-S (excluding classes K633...
8,2024,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,157616,ANZSIC06 divisions A-S (excluding classes K633...
9,2024,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,323,ANZSIC06 divisions A-S (excluding classes K633...
10,2024,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1548,ANZSIC06 divisions A-S (excluding classes K633...

In [19]:
data

[{'name': 'krish', 'age': 25, 'city': 'banglore'},
 {'name': 'John', 'age': 25, 'city': 'banglore'},
 {'name': 'Aman', 'age': 25, 'city': 'banglore'},
 {'name': 'Anand', 'age': 25, 'city': 'banglore'}]

In [ ]:
# using loc function we can get rows data 
df.loc[0]

Year                                                                        2024
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     979594
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [30]:
df.iloc[0:10,2]

0    99999
1    99999
2    99999
3    99999
4    99999
5    99999
6    99999
7    99999
8    99999
9    99999
Name: Industry_code_NZSIOC, dtype: object

In [27]:
df.iloc[0:10]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
5,2024,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,71493,ANZSIC06 divisions A-S (excluding classes K633...
6,2024,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,8540,ANZSIC06 divisions A-S (excluding classes K633...
7,2024,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,32896,ANZSIC06 divisions A-S (excluding classes K633...
8,2024,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,157616,ANZSIC06 divisions A-S (excluding classes K633...
9,2024,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,323,ANZSIC06 divisions A-S (excluding classes K633...

In [35]:
#acceessing a specified element

df['Year']
df.at[55619,'Year']

np.int64(2013)

In [38]:
# accessing a specified element using iat
df.iloc[0:10]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
5,2024,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,71493,ANZSIC06 divisions A-S (excluding classes K633...
6,2024,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,8540,ANZSIC06 divisions A-S (excluding classes K633...
7,2024,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,32896,ANZSIC06 divisions A-S (excluding classes K633...
8,2024,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,157616,ANZSIC06 divisions A-S (excluding classes K633...
9,2024,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,323,ANZSIC06 divisions A-S (excluding classes K633...

In [40]:
df.iat[2,8]

'112188'

In [41]:
# data maniplulation with dataframe
data = { 
    'name' : ['krish', 'John','jack' ],
    "age" : [25,30,45],
    "city":['inodre','new york','florida']
}
df = pd.DataFrame(data=data)
print(df)

    name  age      city
0  krish   25    inodre
1   John   30  new york
2   jack   45   florida

In [ ]:
# adding column to dataframe
df['salary'] =[5000,6000,7000]
df

    name  age      city  salary
0  krish   25    inodre    5000
1   John   30  new york    6000
2   jack   45   florida    7000

In [ ]:
df.drop('salary' , axis= 1)// in this case it will check in column
df.drop('salary' , axis= 0)// in this case it will chech in rows

    name  age      city
0  krish   25    inodre
1   John   30  new york
2   jack   45   florida

In [48]:
df

    name  age      city  salary
0  krish   25    inodre    5000
1   John   30  new york    6000
2   jack   45   florida    7000

In [49]:
df.drop('salary',axis =1, inplace= True )

In [50]:
df

    name  age      city
0  krish   25    inodre
1   John   30  new york
2   jack   45   florida

In [54]:
## Add age to column
df['age'] = df['age']+1
df

    name  age      city
0  krish   27    inodre
1   John   32  new york
2   jack   47   florida

In [55]:
# drop row based on column index
df.drop(0)

   name  age      city
1  John   32  new york
2  jack   47   florida

In [60]:
df = pd.read_csv('annual-enterprise.csv')
# display data type of each column
print("data type:", df.dtypes)

# Describe the DataFrame
print("statistical summary :\n" , df.describe())

# print(df.groupby('Year')['Value'].mean())

data type: Year                            int64
Industry_aggregation_NZSIOC    object
Industry_code_NZSIOC           object
Industry_name_NZSIOC           object
Units                          object
Variable_code                  object
Variable_name                  object
Variable_category              object
Value                          object
Industry_code_ANZSIC06         object
dtype: object
statistical summary :
                Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000

In [69]:
df.at[55619,'Value']

'46'