In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('annual-enterprise.csv')
df.describe()

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

               Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000

In [8]:
## handling messing value

In [13]:
df.isnull()
df.isnull().any(axis =1)
df.isnull().any()
df.isnull().sum()
# to find null valude in data

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

In [14]:
#  To fill missing value
df.fillna(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [18]:
#filling missing value with mean if value
df['sales_fillNA'] = df['Year'].fillna(df['Year'].mean())
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,sales_fillNA
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...,2024
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...,2024
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...,2024
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...,2024
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...,2024
...,...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013

In [21]:
# change the data type 
df.dtypes

Year                            int64
Industry_aggregation_NZSIOC    object
Industry_code_NZSIOC           object
Industry_name_NZSIOC           object
Units                          object
Variable_code                  object
Variable_name                  object
Variable_category              object
Value                          object
Industry_code_ANZSIC06         object
sales_fillNA                    int64
dtype: object

In [26]:
## renaming columns 
df.rename(columns = {'Year': 'sales Year'})
df['Value']

0        979594
1        838626
2        112188
3         28781
4        856960
          ...
55615        52
55616        40
55617        12
55618         5
55619        46
Name: Value, Length: 55620, dtype: object

In [27]:
#change datatype 
df['Value_new'] = df['Value'].astype(object)
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,sales_fillNA,Value_new
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...,2024,979594
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...,2024,838626
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...,2024,112188
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...,2024,28781
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...,2024,856960

In [29]:
df['new_Value'] = df['Value'].apply(lambda x: x*2)

In [30]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,sales_fillNA,Value_new,new_Value
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...,2024,979594,979594979594
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...,2024,838626,838626838626
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...,2024,112188,112188112188
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...,2024,28781,2878128781
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...,2024,856960,856960856960
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013,52,5252
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013,40,4040
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013,12,1212
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013,5,55
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",2013,46,4646

In [54]:
## data aggregating and grouping
df=pd.read_csv('products-100.csv')
print(df)
df.head()
# print(df.dtypes)
# grouped_mean = df.groupby('Year')['Value']

# print(f"data :" ,grouped_mean)

    Index                                   Name  \
0       1   Compact Printer Air Advanced Digital
1       2                                 Tablet
2       3                   Smart Blender Cooker
3       4           Advanced Router Rechargeable
4       5           Portable Mouse Monitor Phone
..    ...                                    ...
95     96                                 Router
96     97     Fast Thermostat Microphone Scooter
97     98  Eco Heater Toaster Stove Silent Sense
98     99               Clean Blender Scale Lite
99    100                             Smart Lamp

                                          Description  \
0       Situation organization these memory much off.
1         Discussion loss politics free one thousand.
2                                   No situation per.
3                     For force gas energy six laugh.
4   Feeling back religious however author room sci...
..                                                ...
95                   Investment everything story buy.
96                     Nature notice themselves news.
97                   Understand still or summer rule.
98                               Final art some push.
99                         However public major baby.

                          Brand                Category  Price Currency  \
0       Garner, Boyle and Flynn      Books & Stationery    265      USD
1                   Mueller Inc        Shoes & Footwear    502      USD
2    Lawson, Keller and Winters      Kitchen Appliances    227      USD
3            Gallagher and Sons      Kitchen Appliances    121      USD
4                     Irwin LLC          Kids' Clothing      1      USD
..                          ...                     ...    ...      ...
95                 Atkinson Inc     Laptops & Computers    375      USD
96                     Shea Ltd  Beauty & Personal Care    289      USD
97                     West Ltd       Cleaning Supplies    232      USD
98     Bell, Gamble and Barrett        Camping & Hiking    241      USD
99  Hebert, Hughes and Trujillo          Bedding & Bath     71      USD

    Stock            EAN        Color         Size   Availability  Internal ID
0     774  2091465262179  ForestGreen        Large      pre_order           56
1      81  5286196620740        Black      8x10 in       in_stock           29
2     726  1282898648918    SlateGray           XS       in_stock           70
3     896  3879177514583    PaleGreen            L   discontinued           31
4     925  9055773261265     SeaShell   100x200 mm   discontinued           10
..    ...            ...          ...          ...            ...          ...
95    703  3330396409604    Gainsboro      8x10 in  limited_stock           55
96    727  9265397743935        White  Extra Large      backorder           25
97    998  5505866454530      OldLace        Small  limited_stock           20
98    391  3893594435450   Aquamarine       5x7 in  limited_stock            5
99    518  8264263605712        Brown       Medium  limited_stock            3

[100 rows x 13 columns]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

In [59]:
df.head()

grouped_mean = df.groupby(['Brand', 'Color'])['Price'].mean()
print(grouped_mean)

Brand                      Color
Ali-Oliver                 DarkOrchid      982.0
Atkinson Inc               Gainsboro       375.0
Barker-Murphy              OliveDrab       982.0
Barnes-Glass               LightBlue       640.0
Barron-Little              Violet          511.0
                                           ...
Werner PLC                 LightCoral      259.0
West Ltd                   OldLace         232.0
Whitney Group              BlueViolet      352.0
Williamson PLC             Moccasin        913.0
Zimmerman, Barr and Davis  MediumOrchid    999.0
Name: Price, Length: 100, dtype: float64

In [60]:
from click import group


group_sum= df.groupby(['Brand', 'Color'])['Price'].sum()
print(group_sum)

Brand                      Color
Ali-Oliver                 DarkOrchid      982
Atkinson Inc               Gainsboro       375
Barker-Murphy              OliveDrab       982
Barnes-Glass               LightBlue       640
Barron-Little              Violet          511
                                          ...
Werner PLC                 LightCoral      259
West Ltd                   OldLace         232
Whitney Group              BlueViolet      352
Williamson PLC             Moccasin        913
Zimmerman, Barr and Davis  MediumOrchid    999
Name: Price, Length: 100, dtype: int64

In [61]:
# aggregate multiple functions
grouped_age= df.groupby(['Brand', 'Color'])['Price'].agg(['mean', 'sum','count'])
print(grouped_age)

                                         mean  sum  count
Brand                     Color
Ali-Oliver                DarkOrchid    982.0  982      1
Atkinson Inc              Gainsboro     375.0  375      1
Barker-Murphy             OliveDrab     982.0  982      1
Barnes-Glass              LightBlue     640.0  640      1
Barron-Little             Violet        511.0  511      1
...                                       ...  ...    ...
Werner PLC                LightCoral    259.0  259      1
West Ltd                  OldLace       232.0  232      1
Whitney Group             BlueViolet    352.0  352      1
Williamson PLC            Moccasin      913.0  913      1
Zimmerman, Barr and Davis MediumOrchid  999.0  999      1

[100 rows x 3 columns]

In [65]:
## mering and joining Dataframes
df1= pd.DataFrame({'key' : ['a', 'b','c'], 'Value1':[1,2,3]})
df2= pd.DataFrame({'key' : ['a', 'b','d'], 'Value1':[4,5,6]})
df1

  key  Value1
0   a       1
1   b       2
2   c       3

In [66]:
df2

  key  Value1
0   a       4
1   b       5
2   d       6

In [ ]:

pd.merge(df1, df2 , on="key", how= 'inner')

  key  Value1_x  Value1_y
0   a         1         4
1   b         2         5

In [69]:
pd.merge(df1, df2 , on="key", how= 'outer')

  key  Value1_x  Value1_y
0   a       1.0       4.0
1   b       2.0       5.0
2   c       3.0       NaN
3   d       NaN       6.0

In [70]:
pd.merge(df1, df2 , on="key", how= 'left')

  key  Value1_x  Value1_y
0   a         1       4.0
1   b         2       5.0
2   c         3       NaN

In [71]:
pd.merge(df1, df2 , on="key", how= 'right')

  key  Value1_x  Value1_y
0   a       1.0         4
1   b       2.0         5
2   d       NaN         6